title="We are Studio Zero"
baseURL="//studiozero.co/"

[params]
	name="Studio Zero"
	description = "We are Studio Zero | Immersive Web | VR | AR | MR | AI"
	author="Studio Zero"
	LanguageCode="en-gb"
	PhoneNumber="+447890847106"
	PhoneDisplay="07890 847106"
	Email="hi@studiozero.co"
